### PR TITLE
Make injections.scm compatible with nvim-treesitter

### PR DESCRIPTION
**Pull request by nkrkv**

### CODE REVIEW

**Comment by nkrkv** [comment]
Hello @jaredramirez!

In #63 you’ve brought `injections.scm`, thanks for that. However, I found it is ignored by NVim and I see no highlight for JS embedded in `%raw`. I noticed that `html` language, for example, uses another query structure for its injections: https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/html/injections.scm

I’ve tried to do the same (see “Files Changed” in this PR) and now JS is indeed properly formatted being nested inside ReScript.

I wonder, where did you see a query you’ve based upon initially? Does it work for you? I’m asking because it does not look like some random characters and I don’t want to break anything.

**Comment by jaredramirez** [comment]
I've gotten it to work using the syntax in my PR with the [helix](https://helix-editor.com/) editor.

I got the query in my PR from a couple places:
[tree-sitter/tree-sitter-html](https://github.com/tree-sitter/tree-sitter-html/blob/master/queries/injections.scm)
[elm-tooling/tree-sitter-elm](https://github.com/elm-tooling/tree-sitter-elm/blob/main/queries/injections.scm)

I would guess that `nvim-treesitter` requires a different format. I'm unsure why there'd be a difference though, as the first link is from the official `tree-sitter` org so I assumed that was then indented way.

I don't think there's a harm in including both formats in `injections.scm` though for usages in different editors?

**Comment by nkrkv** [comment]
> I would guess that nvim-treesitter requires a different format

Yeah, looks like indeed that’s the problem

> I don't think there's a harm in including both formats in injections.scm though for usages in different editors?

Would you try the file with both query sets defined side by side and verify Helix is OK with this?

```
((raw_js) @injection.content
 (#set! injection.language "javascript"))

((raw_gql) @injection.content
 (#set! injection.language "graphql"))

(raw_js) @javascript
(raw_gql) @graphql
(comment) @comment
```

**Comment by jaredramirez** [comment]
Tested with Helix and it's all good. Thanks for checking!

**Pull request merged**
