### PR TITLE
Enhancements & fix a few bugs

### PR DESCRIPTION
**Pull request by jaredramirez**
Hey there!

This PR adds some enhancements and fixes a few bugs I found while using this tree sitter in another project! I've updated `grammar.js`, added tests, and have made sure that `make test_wild` runs with no issues. The enhancements/bugs are:

1. Wrap raw JS in it's own node for JS tree sitter injection
2. Parsing mutually recursive type declarations (https://github.com/nkrkv/tree-sitter-rescript/issues/56)
2. Parsing a list of statements in a case branch
3. Having multiple statements in a `%%private(...)`

Sorry theses aren't broken up into multiple PRs. These fixes were just based on use in my projects and I figured others may benefit from them too.

Thanks for the great project!

### CODE REVIEW

**Comment by nkrkv** [comment]
That’s great, thank you a lot! I’m going to test & merge tonight.

**Comment by nkrkv** [comment]
Thank you!

I wonder, you say “Wrap raw JS in its own node for JS tree sitter injection”, do you have JS inside `%raw` highlighted properly? If so, how? Are there some extra scm’s defining what to do with `(raw_js)` to make it happen?

P.S> In this PR I see quite a lot of `$._newline` and `$._statement_delimiter` references that are very low-level and should not leak around `grammar.js`. Now I see, that `scanner.c` needs improvement to properly address the issue, but for now, I merge as-is. Will try to refactor/simplify soon, keeping the resulting behavior intact.

**Comment by jaredramirez** [comment]
I'm working on getting JS properly highlighted! I know it's possible, because HTML tree sitter it can highlight JS and CSS right in the HTML file.

[Here's](https://github.com/tree-sitter/tree-sitter-html/blob/master/queries/injections.scm) the scm file they use to denote it:
```
((script_element
  (raw_text) @injection.content)
 (#set! injection.language "javascript"))

((style_element
  (raw_text) @injection.content)
 (#set! injection.language "css"))
```

I believe with rescript, we could so something like:
```
((raw_js) @injection.content
 (#set! injection.language "javascript"))
```

But I haven't had time to test it yet.

If I can get it to work I'll probably PR something similar for GraphQL as I use the [graphql_ppx](https://github.com/reasonml-community/graphql-ppx) often and I know there's a GraphQL tree sitter.

**Comment by jaredramirez** [comment]
@nkrkv, quick screenshot of JS tree sitter injection in my editor!

Screen Shot 2022-01-14 at 11 42 40 AM

**Pull request merged**
